{ NativeASM | Copyright (c) 2026 Selahattin Erkoc }
{ SPDX-License-Identifier: MIT }
program NativeAsmDemo;

{$APPTYPE CONSOLE}
{$R *.res}

{
  NativeAsm — Demo & Self-Test
  =====================================
  Compile:   dcc64.exe NativeAsmDemo.dpr -B -U..\Source
  Or open in RAD Studio / Delphi and add ..\Source to the library path.

  The demo executes several generated stubs and verifies their results,
  serving double duty as an integration test.  All generated bytes are
  printed so you can cross-check with an external disassembler (ndisasm,
  objdump, Ghidra, …).

  Demos
  -----
  1  Return a constant (basic smoke test)
  2  Add Win64 arguments RCX + RDX
  3  Counted loop sum (TSmartAsmBuilder + string labels)
  4  Conditional branch: max(a, b)
  5  Integer TLabel system  (NewLabel / Bind / J overload)
  6  AlignTo padding (NOP fill)
  7  Register width casts  (AsR32 / AsR8Lo)
  8  Syscall stub byte layout
  9  IAT thunk layout
  10 TExecutableCode via TJitAllocator pool
  11 TConstPool — constant pool finalisation
  12 Hex dump of a small stub
  17 V5 regression suite — negative tests (expected raises) and positive regressions:
       17o EmitArith reg/reg width mismatch, 17p Imul imm16 range,
       17q LoopBegin zero count, 17r VaToRva underflow, 17s TTrampoline nil,
       17t EmitGetRip non-64-bit register,
       17u Add(EAX,$FFFFFFFF) full 32-bit bit pattern accepted,
       17v PushRet 14-byte size, 17w EmitGetRip 7-byte LEA encoding,
       17x TEST immediate encoding, 17y LabelKey null-prefix non-collision
}

uses
  System.SysUtils,
  NativeAsm.Types,
  NativeAsm.Builder,
  NativeAsm.Extensions,
  NativeAsm.JitAlloc,
  NativeAsm.ConstPool,
  NativeAsm.Stubs,
  NativeAsm.Debug;

// ── Test helpers ──────────────────────────────────────────────────────────────

var
  Passed, Failed: Integer;

procedure Check(const Name: string; Expected, Got: UInt64);
begin
  if Expected = Got then
  begin
    Writeln('  PASS  ', Name);
    Inc(Passed);
  end
  else
  begin
    Writeln('  FAIL  ', Name,
      ' — expected ', Expected, ' got ', Got);
    Inc(Failed);
  end;
end;

procedure CheckBool(const Name: string; Cond: Boolean);
begin
  if Cond then
  begin
    Writeln('  PASS  ', Name);
    Inc(Passed);
  end
  else
  begin
    Writeln('  FAIL  ', Name);
    Inc(Failed);
  end;
end;

// ── Demo 1: Return a constant ─────────────────────────────────────────────────

procedure Demo_ReturnConstant;
var
  B: TAsmBuilder;
  R: UInt64;
begin
  Writeln;
  Writeln('=== Demo 1: Return constant 42 ===');
  B := TAsmBuilder.New;
  try
    B.Prolog
     .Mov(TOperand(RAX), TOperand(Int64(42)))
     .Epilog
     .Ret;

    Writeln('  Bytes: ', TAsmDumper.ByteView(B.Build));
    Writeln('  Stats: ', TAsmDumper.StatsText(B.Build));

    R := B.Run;
    Check('ReturnConstant = 42', 42, R);
  finally
    B.Free;
  end;
end;

// ── Demo 2: Add two Win64 arguments ──────────────────────────────────────────

procedure Demo_AddArgs;
var
  B: TAsmBuilder;
  R: UInt64;
begin
  Writeln;
  Writeln('=== Demo 2: Add RCX + RDX (Win64 args 1 & 2) ===');
  B := TAsmBuilder.New;
  try
    B.Prolog
     .Mov(TOperand(RAX), TOperand(RCX))
     .Add(TOperand(RAX), TOperand(RDX))
     .Epilog
     .Ret;

    Writeln('  Bytes: ', TAsmDumper.ByteView(B.Build));
    R := B.Run(10, 32);
    Check('AddArgs(10, 32) = 42', 42, R);
  finally
    B.Free;
  end;
end;

// ── Demo 3: Loop counting ─────────────────────────────────────────────────────

procedure Demo_LoopSum;
var
  B: TSmartAsmBuilder;
  R: UInt64;
begin
  Writeln;
  Writeln('=== Demo 3: Sum 1..10 via counted loop ===');

  B := TSmartAsmBuilder.Create;
  try
    B.Prolog
     .Zero(RAX)                        // RAX = 0 (accumulator)
     .LoopBegin(RDX, 10, 'count')      // RDX = 10; count:
     .Add(TOperand(RAX), TOperand(RDX))// RAX += RDX
     .LoopEnd(RDX, 'count')            // DEC RDX; JNZ count
     .Epilog
     .Ret;

    Writeln('  Bytes: ', TAsmDumper.ByteView(B.Build));
    R := B.Run;
    Check('LoopSum(1..10) = 55', 55, R);
  finally
    B.Free;
  end;
end;

// ── Demo 4: Conditional branch ────────────────────────────────────────────────

procedure Demo_MaxOfTwo;
var
  B: TAsmBuilder;
  R: UInt64;
begin
  Writeln;
  Writeln('=== Demo 4: Max(RCX, RDX) using string label ===');

  B := TAsmBuilder.New;
  try
    B.Prolog
     .Mov(TOperand(RAX), TOperand(RCX))
     .Cmp(TOperand(RAX), TOperand(RDX))
     .J(cond_JGE, 'done')
     .Mov(TOperand(RAX), TOperand(RDX))
     .Label_('done')
     .Epilog
     .Ret;

    Writeln('  Bytes: ', TAsmDumper.ByteView(B.Build));

    R := B.Run(17, 42); Check('Max(17, 42) = 42', 42, R);
    R := B.Run(99,  3); Check('Max(99,  3) = 99', 99, R);
    R := B.Run( 7,  7); Check('Max( 7,  7) =  7',  7, R);
  finally
    B.Free;
  end;
end;

// ── Demo 5: Integer TLabel system ────────────────────────────────────────────

procedure Demo_IntLabel;
var
  B   : TAsmBuilder;
  LDone: TLabel;
  R   : UInt64;
begin
  Writeln;
  Writeln('=== Demo 5: Max(RCX, RDX) using integer TLabel ===');

  B := TAsmBuilder.New;
  try
    LDone := B.NewLabel;  // allocate label ID — not yet positioned

    B.Prolog
     .Mov(TOperand(RAX), TOperand(RCX))
     .Cmp(TOperand(RAX), TOperand(RDX))
     .J(cond_JGE, LDone)              // forward ref to integer label
     .Mov(TOperand(RAX), TOperand(RDX))
     .Bind(LDone)                      // position label here
     .Epilog
     .Ret;

    Writeln('  Bytes: ', TAsmDumper.ByteView(B.Build));

    R := B.Run(3, 99); Check('IntLabel Max(3, 99) = 99', 99, R);
    R := B.Run(50,  1); Check('IntLabel Max(50, 1) = 50', 50, R);
  finally
    B.Free;
  end;
end;

// ── Demo 6: AlignTo padding ───────────────────────────────────────────────────

procedure Demo_AlignTo;
var
  B   : TAsmBuilder;
  Code: TBytes;
  Rem : Integer;
begin
  Writeln;
  Writeln('=== Demo 6: AlignTo(16) NOP padding ===');

  B := TAsmBuilder.New;
  try
    // Emit just a few bytes so the code is not already aligned
    B.Mov(TOperand(RAX), TOperand(Int64(1)));
    B.AlignTo(16);  // pad to 16-byte boundary with NOPs

    Code := B.Build;
    Rem  := Length(Code) mod 16;
    Writeln('  Code size: ', Length(Code), ' bytes');
    Writeln('  Bytes mod 16: ', Rem, '  (should be 0)');
    CheckBool('AlignTo(16) produces multiple-of-16 size', Rem = 0);
  finally
    B.Free;
  end;
end;

// ── Demo 7: Register width casts ─────────────────────────────────────────────

procedure Demo_RegisterCasts;
var
  B   : TAsmBuilder;
  Code: TBytes;
  R   : UInt64;
  XorOff, MovAlClOff: Integer;
begin
  Writeln;
  Writeln('=== Demo 7: Register width casts AsR32 / AsR8Lo ===');

  // XOR EAX, EAX (32-bit XOR → zero-extends to RAX, no REX.W needed)
  // then MOV AL, CL (8-bit byte copy of low arg byte)
  // return value in RAX (AL widened to 64 bits)

  B := TAsmBuilder.New;
  try
    B.Prolog;

    // Record where XOR EAX, EAX starts (after the prolog)
    XorOff := B.CodeSize;
    // XOR EAX, EAX   — AsR32 → rt32 → no REX.W; opcode $33 /r
    // Expected: 33 C0  (no REX prefix; ModRM = 11_000_000)
    B.Xor_(EAX, EAX);

    MovAlClOff := B.CodeSize;
    // MOV AL, CL     — AsR8Lo → rt8 → opcode $8A /r
    // Expected: 8A C1  (no REX; ModRM = 11_000_001)
    B.Mov(AL, CL);

    B.Epilog.Ret;

    Code := B.Build;
    Writeln('  Bytes: ', TAsmDumper.ByteView(Code));

    // Verify XOR EAX, EAX encodes as  33 C0  (not 48 33 C0 with REX.W)
    CheckBool('XOR EAX,EAX byte[0] = $33 (no REX.W)',
      Code[XorOff] = $33);
    CheckBool('XOR EAX,EAX byte[1] = $C0 (ModRM 11_000_000)',
      Code[XorOff + 1] = $C0);

    // Verify MOV AL, CL encodes as  8A C1  (no REX; ModRM /reg=AL=0, r/m=CL=1)
    CheckBool('MOV AL,CL byte[0] = $8A (8-bit MOV r,r/m)',
      Code[MovAlClOff] = $8A);
    CheckBool('MOV AL,CL byte[1] = $C1 (ModRM 11_000_001)',
      Code[MovAlClOff + 1] = $C1);

    // Execute: arg1 = 77 (in RCX), AL should become 77
    R := B.Run(77, 0);
    Check('RegisterCast: AL = CL (arg=77)', 77, R);
  finally
    B.Free;
  end;
end;

// ── Demo 8: Syscall stub ──────────────────────────────────────────────────────

procedure Demo_SyscallStub;
var
  Stub: TBytes;
begin
  Writeln;
  Writeln('=== Demo 8: Syscall stub bytes (NtAllocateVirtualMemory = 0x18) ===');
  Stub := TSyscallStub.Build($18);
  Writeln('  Bytes: ', TAsmDumper.ByteView(Stub));
  Writeln('  Stats: ', TAsmDumper.StatsText(Stub));
  // Expected: 49 89 CA B8 18 00 00 00 0F 05 C3
  TAsmDumper.AssertPrefix(Stub, [$49, $89, $CA, $B8, $18, $00, $00, $00, $0F, $05, $C3]);
  Writeln('  PASS  SyscallStub bytes verified');
  Inc(Passed);
end;

// ── Demo 9: IAT thunk layout ──────────────────────────────────────────────────

procedure Demo_IatThunk;
var
  Thunk: TIatThunk;
begin
  Writeln;
  Writeln('=== Demo 9: IAT thunk layout ===');
  Thunk := TIatThunk.Build(nil);
  Writeln('  Bytes: ', TAsmDumper.ByteView(Thunk.Stub));
  Writeln('  AddressOffset: ', Thunk.AddressOffset);
  TAsmDumper.AssertPrefix(Thunk.Stub, [$FF, $25, $00, $00, $00, $00]);
  Writeln('  PASS  IatThunk prefix verified');
  Inc(Passed);
end;

// ── Demo 10: TJitAllocator pool ───────────────────────────────────────────────

procedure Demo_JitAllocator;
var
  Alloc: TJitAllocator;
  Exe1 : TExecutableCode;
  Exe2 : TExecutableCode;
  B1, B2: TAsmBuilder;
  R    : UInt64;
begin
  Writeln;
  Writeln('=== Demo 10: TExecutableCode via TJitAllocator pool ===');

  Alloc := TJitAllocator.Create;
  B1    := TAsmBuilder.New;
  B2    := TAsmBuilder.New;
  try
    // Stub 1: return 111
    B1.Prolog.Mov(TOperand(RAX), TOperand(Int64(111))).Epilog.Ret;
    // Stub 2: return 222
    B2.Prolog.Mov(TOperand(RAX), TOperand(Int64(222))).Epilog.Ret;

    Exe1 := TExecutableCode.FromBuilder(B1, False, Alloc);
    Exe2 := TExecutableCode.FromBuilder(B2, False, Alloc);
    try
      R := Exe1.Run;
      Check('JitAlloc Exe1 = 111', 111, R);
      R := Exe2.Run;
      Check('JitAlloc Exe2 = 222', 222, R);

      Writeln(Format('  Allocator: %d chunk(s), %d bytes allocated, %d used',
        [Alloc.ChunkCount, Alloc.TotalAllocated, Alloc.TotalUsed]));
    finally
      Exe1.Free;
      Exe2.Free;
    end;
  finally
    B1.Free;
    B2.Free;
    Alloc.Free;
  end;
end;

// ── Demo 11: TConstPool ───────────────────────────────────────────────────────

procedure Demo_ConstPool;
var
  Pool   : TConstPool;
  Code   : TBytes;
  SlotA  : Integer;
  SlotA2 : Integer;
begin
  Writeln;
  Writeln('=== Demo 11: TConstPool deduplication and layout ===');

  Pool := TConstPool.Create;
  try
    SlotA  := Pool.AddDouble(3.14159);
    SlotA2 := Pool.AddDouble(3.14159);   // should return same slot (dedup)
    Pool.AddUInt64($DEADBEEFCAFE1234);
    Pool.AddSingle(2.71828);

    CheckBool('ConstPool dedup: same value → same slot', SlotA = SlotA2);
    CheckBool('ConstPool EntryCount = 3 (deduped)', Pool.EntryCount = 3);

    Writeln(Format('  EntryCount: %d, PoolSize: %d bytes',
      [Pool.EntryCount, Pool.PoolSize]));

    // Finalize on an empty code buffer to inspect the pool layout
    SetLength(Code, 0);
    Code := Pool.Finalize(Code);
    Writeln('  Pool bytes: ', TAsmDumper.ByteView(Code));
    CheckBool('ConstPool Finalize produces non-empty result', Length(Code) > 0);
  finally
    Pool.Free;
  end;
end;

// ── Demo 12: Hex dump ─────────────────────────────────────────────────────────

procedure Demo_HexDump;
var
  B: TAsmBuilder;
begin
  Writeln;
  Writeln('=== Demo 12: Hex dump of a small stub ===');
  B := TAsmBuilder.New;
  try
    B.Prolog
     .Xor_(TOperand(RAX), TOperand(RAX))
     .Mov(TOperand(RAX), TOperand(RCX))
     .Add(TOperand(RAX), TOperand(RDX))
     .Imul(RAX, RAX, 7)
     .Epilog
     .Ret;

    Write(TAsmDumper.HexDump(B.Build, $1000));
  finally
    B.Free;
  end;
end;

// ── Demo 13: 8-bit arithmetic opcodes ─────────────────────────────────────────
// Verifies that the correct $00/$02/$80 opcode family is emitted for 8-bit
// operands and that the generated code produces the right result at runtime.

procedure Demo_8BitArithmetic;
var
  B   : TAsmBuilder;
  Code: TBytes;
  Off : Integer;
  R   : UInt64;
begin
  Writeln;
  Writeln('=== Demo 13: 8-bit arithmetic opcodes ===');

  // ── byte-exact check: ADD AL, CL (register-register)
  // Expected encoding: 02 C1
  //   $02 = ADD r8, r/m8   /reg=AL=0, /rm=CL=1 → ModRM = 11_000_001 = C1
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Add(TOperand(AL), TOperand(CL));
    Code := B.Build;
    CheckBool('ADD AL,CL opcode = $02 (r8 ← r/m8)',  Code[Off]     = $02);
    CheckBool('ADD AL,CL ModRM  = $C1 (11_000_001)',  Code[Off + 1] = $C1);
  finally B.Free; end;

  // ── byte-exact check: ADD AL, 42 (immediate)
  // Expected encoding: 80 C0 2A
  //   $80 /0 ib: /ext=0 (ADD), /rm=AL=0, Mod=11 → ModRM=C0, imm8=2A
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Add(TOperand(AL), TOperand(Integer(42)));
    Code := B.Build;
    CheckBool('ADD AL,42 opcode = $80 (r/m8, imm8)',  Code[Off]     = $80);
    CheckBool('ADD AL,42 ModRM  = $C0 (11_000_000)',   Code[Off + 1] = $C0);
    CheckBool('ADD AL,42 imm8   = $2A (42)',            Code[Off + 2] = $2A);
  finally B.Free; end;

  // ── byte-exact check: SUB DL, BL
  // $28 = SUB r/m8, r8  (when Dest is register, builder uses $2A = r8 ← r/m8)
  // Expected: 2A D3  (/reg=DL=2, /rm=BL=3 → ModRM=11_010_011=D3)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Sub(TOperand(DL), TOperand(BL));
    Code := B.Build;
    CheckBool('SUB DL,BL opcode = $2A (r8 ← r/m8)',  Code[Off]     = $2A);
    CheckBool('SUB DL,BL ModRM  = $D3 (11_010_011)',  Code[Off + 1] = $D3);
  finally B.Free; end;

  // ── runtime: ADD AL, DL (arg1 low byte + arg2 low byte)
  // fn(5, 3) → AL = 5+3 = 8; RAX = 8 (upper bits zeroed by MOV EAX,0)
  B := TAsmBuilder.New;
  try
    B.Mov(TOperand(EAX), TOperand(Integer(0)))  // MOV EAX, 0  (zero-extends RAX)
     .Mov(TOperand(AL), TOperand(CL))           // AL = arg1 low byte
     .Add(TOperand(AL), TOperand(DL))           // ADD AL, DL
     .Ret;
    R := B.Run(5, 3);
    Check('8-bit ADD: fn(5,3) = 8', 8, R);
  finally B.Free; end;

  // ── runtime: XOR BL, BL → BL = 0; then MOV EAX, EBX
  B := TAsmBuilder.New;
  try
    B.Mov(TOperand(EBX), TOperand(ECX))         // EBX = arg1
     .Xor_(TOperand(BL), TOperand(BL))          // BL ^= BL → 0
     .Mov(TOperand(EAX), TOperand(EBX))         // EAX = EBX (BL=0, upper EBX bits)
     .Ret;
    R := B.Run($DEADBEEF);
    // arg1=$DEADBEEF; EBX=$DEADBEEF; BL^=BL→BL=0; EAX = $DEAD BE 00
    Check('8-bit XOR BL,BL → BL=0: fn($DEADBEEF) = $DEADBE00',
      $DEADBE00, R);
  finally B.Free; end;
end;

// ── Demo 14: MOV immediate width dispatch ─────────────────────────────────────
// Verifies B0+rb for rt8, 66 B8+rw for rt16, B8+rd for rt32,
// and REX.W C7 / B8+rq for rt64.

procedure Demo_MovImmWidth;
var
  B   : TAsmBuilder;
  Code: TBytes;
  Off : Integer;
  R   : UInt64;
begin
  Writeln;
  Writeln('=== Demo 14: MOV immediate width dispatch ===');

  // MOV AL, $5A  →  B0 5A  (B0+0=B0 for AL; no REX)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Mov(TOperand(AL), TOperand(Integer($5A)));
    Code := B.Build;
    CheckBool('MOV AL,$5A opcode = $B0',  Code[Off]     = $B0);
    CheckBool('MOV AL,$5A imm    = $5A',  Code[Off + 1] = $5A);
  finally B.Free; end;

  // MOV AX, $1234  →  66 B8 34 12  (66 prefix + B8+0 + imm16 LE)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Mov(TOperand(AX), TOperand(Integer($1234)));
    Code := B.Build;
    CheckBool('MOV AX,$1234 prefix = $66',        Code[Off]     = $66);
    CheckBool('MOV AX,$1234 opcode = $B8',        Code[Off + 1] = $B8);
    CheckBool('MOV AX,$1234 imm16_lo = $34',      Code[Off + 2] = $34);
    CheckBool('MOV AX,$1234 imm16_hi = $12',      Code[Off + 3] = $12);
  finally B.Free; end;

  // MOV EAX, $12345678  →  B8 78 56 34 12  (no REX.W; upper 32 bits zeroed)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Mov(TOperand(EAX), TOperand(Integer($12345678)));
    Code := B.Build;
    CheckBool('MOV EAX,$12345678 opcode = $B8 (no REX)',  Code[Off] = $B8);
    CheckBool('MOV EAX,$12345678 imm32_b0 = $78',         Code[Off + 1] = $78);
    CheckBool('MOV EAX,$12345678 imm32_b3 = $12',         Code[Off + 4] = $12);
  finally B.Free; end;

  // Runtime: MOV EAX, 99  →  return 99
  B := TAsmBuilder.New;
  try
    B.Mov(TOperand(EAX), TOperand(Integer(99))).Ret;
    R := B.Run;
    Check('MOV EAX,99 runtime = 99', 99, R);
  finally B.Free; end;

  // AH MOV: MOV AH, $FF  →  B4 FF  (B0+ModRMField=4+0=B4)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Mov(TOperand(AH), TOperand(Integer($FF)));
    Code := B.Build;
    CheckBool('MOV AH,$FF opcode = $B4 (no REX)',  Code[Off]     = $B4);
    CheckBool('MOV AH,$FF imm    = $FF',            Code[Off + 1] = $FF);
  finally B.Free; end;
end;

// ── Demo 15: Shift width auto-detection ───────────────────────────────────────
// Verifies that the D0/C0/D2 opcode family is used for 8-bit operands and
// D1/C1/D3 (with optional REX.W) for 16/32/64-bit operands.

procedure Demo_ShiftWidth;
var
  B   : TAsmBuilder;
  Code: TBytes;
  Off : Integer;
  R   : UInt64;
begin
  Writeln;
  Writeln('=== Demo 15: Shift width auto-detection ===');

  // SHL AL, 1  →  D0 E0  (D0 = r/m8 by 1; /reg=4 SHL; AL→C0 | E0)
  // ModRM: Mod=11, /reg=4, /rm=AL=0 → 11_100_000 = E0
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Shl_(TOperand(AL), TOperand(Int64(1)));
    Code := B.Build;
    CheckBool('SHL AL,1 opcode = $D0 (r/m8 by 1)',  Code[Off]     = $D0);
    CheckBool('SHL AL,1 ModRM  = $E0 (11_100_000)', Code[Off + 1] = $E0);
  finally B.Free; end;

  // SHL AL, 3  →  C0 E0 03  (C0 = r/m8 by imm8)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Shl_(TOperand(AL), TOperand(Int64(3)));
    Code := B.Build;
    CheckBool('SHL AL,3 opcode = $C0 (r/m8 by imm8)',  Code[Off]     = $C0);
    CheckBool('SHL AL,3 ModRM  = $E0',                  Code[Off + 1] = $E0);
    CheckBool('SHL AL,3 imm8   = 3',                    Code[Off + 2] = 3);
  finally B.Free; end;

  // SHL EAX, 1  →  D1 E0  (D1 = r/m32 by 1; no REX.W)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Shl_(TOperand(EAX), TOperand(Int64(1)));
    Code := B.Build;
    CheckBool('SHL EAX,1 opcode = $D1 (no REX prefix)',  Code[Off]     = $D1);
    CheckBool('SHL EAX,1 ModRM  = $E0',                  Code[Off + 1] = $E0);
  finally B.Free; end;

  // SHL RAX, 1  →  48 D1 E0  (REX.W prefix for 64-bit)
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Shl_(TOperand(RAX), TOperand(Int64(1)));
    Code := B.Build;
    CheckBool('SHL RAX,1 REX.W  = $48',   Code[Off]     = $48);
    CheckBool('SHL RAX,1 opcode = $D1',   Code[Off + 1] = $D1);
    CheckBool('SHL RAX,1 ModRM  = $E0',   Code[Off + 2] = $E0);
  finally B.Free; end;

  // Runtime: SHL ECX by 2 → arg * 4
  B := TAsmBuilder.New;
  try
    B.Mov(TOperand(EAX), TOperand(ECX))
     .Shl_(TOperand(EAX), TOperand(Int64(2)))  // EAX <<= 2
     .Ret;
    R := B.Run(5);
    Check('SHL EAX,2 runtime: fn(5) = 20', 20, R);
  finally B.Free; end;
end;

// ── Demo 16: IMUL 32-bit ──────────────────────────────────────────────────────
// Verifies IMUL r32, r/m32 does not emit REX.W.

procedure Demo_Imul32;
var
  B   : TAsmBuilder;
  Code: TBytes;
  Off : Integer;
  R   : UInt64;
begin
  Writeln;
  Writeln('=== Demo 16: IMUL 32-bit (no REX.W) ===');

  // IMUL EAX, ECX  →  0F AF C1  (no REX prefix at all)
  // /reg=EAX=0, /rm=ECX=1 → ModRM = 11_000_001 = C1
  B := TAsmBuilder.New;
  try
    Off := B.CodeSize;
    B.Imul(EAX, ECX);
    Code := B.Build;
    CheckBool('IMUL EAX,ECX: no REX prefix (byte[0]=$0F)',  Code[Off]     = $0F);
    CheckBool('IMUL EAX,ECX: byte[1] = $AF',                Code[Off + 1] = $AF);
    CheckBool('IMUL EAX,ECX: ModRM   = $C1 (11_000_001)',   Code[Off + 2] = $C1);
  finally B.Free; end;

  // Runtime: EAX = ECX * 7 (3-operand imm form)
  B := TAsmBuilder.New;
  try
    B.Imul(EAX, ECX, 7).Ret;  // IMUL EAX, ECX, 7
    R := B.Run(6);
    Check('IMUL EAX,ECX,7 runtime: fn(6) = 42', 42, R);
  finally B.Free; end;
end;

// ── Demo 17: V5 negative tests ────────────────────────────────────────────────
// Each sub-case EXPECTS an exception.  Failure to raise = bug.

procedure CheckRaises(const Name: string; Proc: TProc);
begin
  try
    Proc();
    Writeln('  FAIL  ', Name, ' — expected exception but none was raised');
    Inc(Failed);
  except
    on E: Exception do
    begin
      Writeln('  PASS  ', Name, ' [', E.ClassName, ': ', E.Message, ']');
      Inc(Passed);
    end;
  end;
end;

procedure Demo_NegativeCases;
var
  B    : TAsmBuilder;
  Alloc: TJitAllocator;
  R    : UInt64;
  Bytes: TBytes;
  LInt : TLabel;
begin
  Writeln;
  Writeln('=== Demo 17: V5 negative test cases (expected exceptions) ===');

  // ── 17a: TLabel ID=0 sentinel must be rejected by Bind ───────────────────
  CheckRaises('Bind(Default(TLabel)) raises — ID=0 is invalid sentinel',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Bind(Default(TLabel)); finally B.Free; end;
    end);

  // ── 17b: Shift: non-CL register count ────────────────────────────────────
  // DL is RDX as rt8 — not CL, must raise
  CheckRaises('Shl_(RAX, DL) raises — shift count must be exactly CL',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Shl_(TOperand(RAX), TOperand(DL)); finally B.Free; end;
    end);

  // ── 17c: Shift: immediate count out of 0..63 ─────────────────────────────
  CheckRaises('Shl_(RAX, 64) raises — immediate 64 out of range 0..63',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Shl_(TOperand(RAX), TOperand(Int64(64))); finally B.Free; end;
    end);

  // ── 17d: Mov reg←reg: width mismatch ─────────────────────────────────────
  CheckRaises('Mov(RAX, EAX) raises — rt64 ≠ rt32',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Mov(TOperand(RAX), TOperand(EAX)); finally B.Free; end;
    end);

  // ── 17e: Movsx: sz64 source is illegal (only sz8/sz16/sz32 valid) ─────────
  CheckRaises('Movsx(RAX, QWordPtr) raises — sz64 source invalid',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Movsx(RAX, TOperand(QWordPtr(ridRAX))); finally B.Free; end;
    end);

  // ── 17f: Movzx: sz32 source is illegal (only sz8/sz16 valid) ─────────────
  CheckRaises('Movzx(EAX, DWordPtr) raises — sz32 source invalid for Movzx',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Movzx(EAX, TOperand(DWordPtr(ridRAX))); finally B.Free; end;
    end);

  // ── 17g: Setcc with a non-8-bit destination register ─────────────────────
  CheckRaises('Setcc(cond_JE, EAX) raises — CMOVcc dest must be 8-bit',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Setcc(cond_JE, EAX); finally B.Free; end;
    end);

  // ── 17h: Call with a 32-bit register ─────────────────────────────────────
  CheckRaises('Call(TOperand(EAX)) raises — CALL needs a 64-bit register',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Call(TOperand(EAX)); finally B.Free; end;
    end);

  // ── 17i: Push with a 32-bit register ─────────────────────────────────────
  CheckRaises('Push(TOperand(EAX)) raises — PUSH has no 32-bit form in 64-bit mode',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Push(TOperand(EAX)); finally B.Free; end;
    end);

  // ── 17j: Imul 2-op width mismatch ────────────────────────────────────────
  CheckRaises('Imul(RAX, EAX) raises — dest rt64 ≠ src rt32',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Imul(RAX, EAX); finally B.Free; end;
    end);

  // ── 17k: Bswap on non-64-bit register ────────────────────────────────────
  CheckRaises('Bswap(EAX) raises — only 64-bit registers supported',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Bswap(EAX); finally B.Free; end;
    end);

  // ── 17l: Cmov with 8-bit destination ─────────────────────────────────────
  CheckRaises('Cmov(cond_JE, AL, AL) raises — CMOVcc has no 8-bit form',
    procedure
    begin
      B := TAsmBuilder.New;
      try B.Cmov(cond_JE, AL, AL); finally B.Free; end;
    end);

  // ── 17m: JitAlloc.Commit with a foreign pointer ───────────────────────────
  CheckRaises('JitAlloc.Commit(Pointer(1), 4) raises — ptr not in any chunk',
    procedure
    begin
      Alloc := TJitAllocator.Create;
      try
        Alloc.Commit(Pointer(1), 4);  // nothing allocated yet → not in any chunk
      finally
        Alloc.Free;
      end;
    end);

  // ── 17n: POSITIVE — MOV r32, -1 must NOT raise (V4 wrongly rejected it) ──
  // MOV EAX, -1  encodes as  B8 FF FF FF FF  (imm32 = $FFFFFFFF)
  // CPU zero-extends: RAX = $00000000_FFFFFFFF
  Writeln;
  Writeln('  --- positive regression for V4 MOV r32 negative-imm bug ---');
  B := TAsmBuilder.New;
  try
    B.Mov(TOperand(EAX), TOperand(Integer(-1))).Ret;
    R := B.Run;
    Check('MOV EAX,-1 accepted and returns $FFFFFFFF', $FFFFFFFF, R);
  finally
    B.Free;
  end;

  // ── 17o: EmitArith reg/reg width mismatch must raise (V5 fix) ────────────
  // Old code derived width only from Dest: Add(RAX, ECX) silently encoded as
  // ADD RAX, RCX because REX.W promoted ECX.  Now it must raise immediately.
  CheckRaises('Add(RAX, ECX) raises — rt64 ≠ rt32 source width mismatch',
    procedure
    var LB: TAsmBuilder;
    begin
      LB := TAsmBuilder.New;
      try LB.Add(TOperand(RAX), TOperand(ECX)); finally LB.Free; end;
    end);

  // ── 17p: Imul 3-op imm16 out of range must raise (V5 fix) ────────────────
  // Old code: WriteInt16(Word(40000)) silently truncated to $0D40 = 3392.
  // Now raises before any byte is emitted.
  CheckRaises('Imul(AX, AX, 70000) raises — 70000 > 65535, out of imm16 range',
    procedure
    var LB: TAsmBuilder;
    begin
      LB := TAsmBuilder.New;
      try LB.Imul(AX, AX, 70000); finally LB.Free; end;
    end);

  // ── 17q: LoopBegin(reg, 0) must raise (V5 fix) ───────────────────────────
  // Count=0 → MOV reg,0 → body executes once → DEC → $FFFF… → JNE loops 2^64 times.
  CheckRaises('LoopBegin(RDX, 0, ''lbl'') raises — zero count produces infinite loop',
    procedure
    var LSB: TSmartAsmBuilder;
    begin
      LSB := TSmartAsmBuilder.Create;
      try LSB.LoopBegin(RDX, 0, 'lbl'); finally LSB.Free; end;
    end);

  // ── 17r: VaToRva underflow must raise (V5 fix) ───────────────────────────
  // VA < ImageBase → delta wraps around as Cardinal underflow.  Now raises.
  CheckRaises('VaToRva(nil, $1000) raises — VA below ImageBase',
    procedure
    begin
      TPicHelper.VaToRva(nil, Pointer(NativeUInt($1000)));
    end);

  // ── 17s: TTrampoline.Build with nil OriginalFn must raise (V5 fix) ────────
  // Old code: Pointer(NativeUInt(nil) + Offset) jumped to an arbitrary low address.
  CheckRaises('TTrampoline.Build(nil, bytes) raises — OriginalFn must not be nil',
    procedure
    begin
      TTrampoline.Build(nil, [$90, $90, $90, $90, $90]);
    end);

  // ── 17t: EmitGetRip with non-64-bit register must raise (V5 fix) ─────────
  // Old CALL/POP approach had no width validation.  LEA replacement validates.
  CheckRaises('EmitGetRip(EAX) raises — destination must be a 64-bit register',
    procedure
    var LB: TAsmBuilder;
    begin
      LB := TAsmBuilder.New;
      try TPicHelper.EmitGetRip(LB, EAX); finally LB.Free; end;
    end);

  // ── 17u: POSITIVE — Add(EAX, $FFFFFFFF) full 32-bit bit pattern (V5 fix) ─
  // Old code: range check was Low(Integer)..High(Integer), rejecting $FFFFFFFF.
  // Fix: 32-bit arithmetic accepts the full 32-bit bit pattern.
  Writeln;
  Writeln('  --- positive regression for 32-bit arith imm32 full range ---');
  B := TAsmBuilder.New;
  try
    // XOR EAX,EAX then ADD EAX,$FFFFFFFF → EAX = $FFFFFFFF (all-ones)
    B.Xor_(TOperand(EAX), TOperand(EAX))
     .Add(TOperand(EAX), TOperand(Int64($FFFFFFFF)))
     .Ret;
    R := B.Run;
    Check('Add(EAX, $FFFFFFFF) accepted; EAX=0+$FFFFFFFF=$FFFFFFFF', $FFFFFFFF, R);
  finally
    B.Free;
  end;

  // ── 17v: POSITIVE — PushRet produces exactly 14 bytes (V5 fix) ───────────
  // Old code: SetLength(Result,13) + Result[12]:=$C3 overwrote the last byte
  // of the Hi32 payload.  Fix: SetLength(Result,14) + Result[13]:=$C3.
  Writeln;
  Writeln('  --- positive regression for PushRet 14-byte size ---');
  Bytes := TPicHelper.PushRet(Pointer(NativeUInt($1122334455667788)));
  CheckBool('PushRet produces exactly 14 bytes (5 PUSH imm32 + 8 MOV[RSP+4] + 1 RET)',
    Length(Bytes) = 14);
  // Byte 13 (0-based) must be $C3 (RET)
  CheckBool('PushRet byte[13] = $C3 (RET opcode at correct offset)',
    (Length(Bytes) = 14) and (Bytes[13] = $C3));

  // ── 17w: POSITIVE — EmitGetRip(RAX) produces 7-byte LEA [RIP+0] (V5 fix) ─
  // Old CALL/POP was CET-unsafe and varied in size.  LEA is always exactly 7 bytes.
  Writeln;
  Writeln('  --- positive regression for EmitGetRip LEA encoding ---');
  B := TAsmBuilder.New;
  try
    TPicHelper.EmitGetRip(B, RAX);
    Bytes := B.Build;
    // Expected: 48 8D 05 00 00 00 00
    //           REX.W LEA ModRM(00,000,101) imm32=0
    CheckBool('EmitGetRip(RAX) produces exactly 7 bytes', Length(Bytes) = 7);
    CheckBool('EmitGetRip(RAX) byte[0]=$48 (REX.W, no REX.R/B)',
      (Length(Bytes) >= 1) and (Bytes[0] = $48));
    CheckBool('EmitGetRip(RAX) byte[1]=$8D (LEA opcode)',
      (Length(Bytes) >= 2) and (Bytes[1] = $8D));
    CheckBool('EmitGetRip(RAX) byte[2]=$05 (ModRM: mod=00 reg=RAX r/m=101=RIP-rel)',
      (Length(Bytes) >= 3) and (Bytes[2] = $05));
  finally
    B.Free;
  end;

  // ── 17x: POSITIVE — TEST AL, imm8 must build without exception (V5 fix) ──
  // Old code: TEST with otImm fell off the end of Test(); the immediate was never
  // encoded.  Fix implements F6/F7 /0 encoding.
  Writeln;
  Writeln('  --- positive regression for TEST immediate encoding ---');
  B := TAsmBuilder.New;
  try
    B.Test(TOperand(AL), TOperand(Int64($FF))).Ret;
    Bytes := B.Build;
    // TEST AL,$FF → F6 C0 FF (3 bytes) — no REX needed for AL
    CheckBool('Test(AL, $FF) builds without exception', Length(Bytes) > 0);
    CheckBool('Test(AL, $FF) byte[0]=$F6 (TEST r/m8 opcode)',
      (Length(Bytes) >= 1) and (Bytes[0] = $F6));
  finally
    B.Free;
  end;

  // ── 17y: POSITIVE — Integer label and string '#1' must NOT collide (V5 fix) ─
  // Old LabelKey: '#' + IntToStr(1) = '#1' → same key as Label_('#1').
  // Fix: #0 + IntToStr(1) → null-char prefix that Pascal string literals cannot
  // produce, so the two label namespaces are permanently disjoint.
  Writeln;
  Writeln('  --- positive regression for LabelKey null-prefix non-collision ---');
  B := TAsmBuilder.New;
  try
    // Place string label '#1' first, then bind integer label — must coexist.
    B.Label_('#1');
    B.Mov(TOperand(RAX), TOperand(Int64(1)));
    LInt := B.NewLabel;       // gets ID=1 → key = #0'1'  (not '#1')
    B.Bind(LInt);
    B.Mov(TOperand(RAX), TOperand(Int64(2)));
    B.Ret;
    Bytes := B.Build;         // must not raise "duplicate label" error
    CheckBool('Integer label 1 and string label ''#1'' coexist without collision',
      Length(Bytes) > 0);
  finally
    B.Free;
  end;
end;

// ── Main ──────────────────────────────────────────────────────────────────────

begin
  Writeln('NativeAsm — Demo / Self-Test');
  Writeln('=====================================');

  Passed := 0;
  Failed := 0;

  try
    Demo_ReturnConstant;
    Demo_AddArgs;
    Demo_LoopSum;
    Demo_MaxOfTwo;
    Demo_IntLabel;
    Demo_AlignTo;
    Demo_RegisterCasts;
    Demo_SyscallStub;
    Demo_IatThunk;
    Demo_JitAllocator;
    Demo_ConstPool;
    Demo_HexDump;
    Demo_8BitArithmetic;
    Demo_MovImmWidth;
    Demo_ShiftWidth;
    Demo_Imul32;
    Demo_NegativeCases;

    Writeln;
    Writeln('=====================================');
    Writeln(Format('Results: %d passed, %d failed', [Passed, Failed]));

    if Failed > 0 then
      ExitCode := 1;

  except
    on E: Exception do
    begin
      Writeln('FATAL: ', E.ClassName, ': ', E.Message);
      ExitCode := 2;
    end;
  end;

  if DebugHook <> 0 then
  begin
    Writeln; Write('Press Enter to exit...'); Readln;
  end;
end.
