unit NativeAsm.Bmi.Db.Generated;

interface

uses
  NativeAsm.Bmi.Db;

const
  CBmiDbSourceSha256 = '0bc3fde0376e3c7db93ce1fa6da35b9d69b868db738e60dba382a2bee54d1f48';
  CBmiMnemonicCount = 13;
  CBmiFormCount = 26;
  CBmiOperandCount = 72;

  CBmiMnemonicNames: array[0..12] of string = (
    'andn',
    'bextr',
    'blsi',
    'blsmsk',
    'blsr',
    'bzhi',
    'mulx',
    'pdep',
    'pext',
    'rorx',
    'sarx',
    'shlx',
    'shrx'
  );

  CBmiMnemonicFormStart: array[0..12] of Word = (
    0,
    2,
    4,
    6,
    8,
    10,
    12,
    14,
    16,
    18,
    20,
    22,
    24
  );

  CBmiMnemonicFormCount: array[0..12] of Word = (
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2
  );

  CBmiFormOrder: array[0..25] of Word = (
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25
  );

  CBmiSourceSignatures: array[0..25] of string = (
    'andn       W:ry, R:ry, R:ry/my',
    'andn       W:ry, R:ry, R:ry/my',
    'bextr      W:ry, R:ry/my, R:ry',
    'bextr      W:ry, R:ry/my, R:ry',
    'blsi       W:ry, R:ry/my',
    'blsi       W:ry, R:ry/my',
    'blsmsk     W:ry, R:ry/my',
    'blsmsk     W:ry, R:ry/my',
    'blsr       W:ry, R:ry/my',
    'blsr       W:ry, R:ry/my',
    'bzhi       W:ry, R:ry/my, R:ry',
    'bzhi       W:ry, R:ry/my, R:ry',
    'mulx       W:ry, W:ry, ~ry/my, ~<dxy>',
    'mulx       W:ry, W:ry, ~ry/my, ~<dxy>',
    'pdep       W:ry, ry, ry/my',
    'pdep       W:ry, ry, ry/my',
    'pext       W:ry, ry, ry/my',
    'pext       W:ry, ry, ry/my',
    'rorx       W:ry, ry/my, imm8',
    'rorx       W:ry, ry/my, imm8',
    'sarx       W:ry, ry/my, ry',
    'sarx       W:ry, ry/my, ry',
    'shlx       W:ry, ry/my, ry',
    'shlx       W:ry, ry/my, ry',
    'shrx       W:ry, ry/my, ry',
    'shrx       W:ry, ry/my, ry'
  );

  CBmiSourceEncodings: array[0..25] of string = (
    '[RVM] VEX.LZ.0F38.Wy F2 /r',
    '[RVM] VEX.LZ.0F38.Wy F2 /r',
    '[RMV] VEX.LZ.0F38.Wy F7 /r',
    '[RMV] VEX.LZ.0F38.Wy F7 /r',
    '[VM ] VEX.LZ.0F38.Wy F3 /3',
    '[VM ] VEX.LZ.0F38.Wy F3 /3',
    '[VM ] VEX.LZ.0F38.Wy F3 /2',
    '[VM ] VEX.LZ.0F38.Wy F3 /2',
    '[VM ] VEX.LZ.0F38.Wy F3 /1',
    '[VM ] VEX.LZ.0F38.Wy F3 /1',
    '[RMV] VEX.LZ.0F38.Wy F5 /r',
    '[RMV] VEX.LZ.0F38.Wy F5 /r',
    '[RVM] VEX.LZ.F2.0F38.Wy F6 /r',
    '[RVM] VEX.LZ.F2.0F38.Wy F6 /r',
    '[RVM] VEX.LZ.F2.0F38.Wy F5 /r',
    '[RVM] VEX.LZ.F2.0F38.Wy F5 /r',
    '[RVM] VEX.LZ.F3.0F38.Wy F5 /r',
    '[RVM] VEX.LZ.F3.0F38.Wy F5 /r',
    '[RM ] VEX.LZ.F2.0F3A.Wy F0 /r ib',
    '[RM ] VEX.LZ.F2.0F3A.Wy F0 /r ib',
    '[RMV] VEX.LZ.F3.0F38.Wy F7 /r',
    '[RMV] VEX.LZ.F3.0F38.Wy F7 /r',
    '[RMV] VEX.LZ.66.0F38.Wy F7 /r',
    '[RMV] VEX.LZ.66.0F38.Wy F7 /r',
    '[RMV] VEX.LZ.F2.0F38.Wy F7 /r',
    '[RMV] VEX.LZ.F2.0F38.Wy F7 /r'
  );

  CBmiOperands: array[0..71] of TBmiDbOperandSpec = (
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$04; RegClass:brcNone; MemClass:bmcNone; ImmBytes:1),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$04; RegClass:brcNone; MemClass:bmcNone; ImmBytes:1),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc32; MemClass:bmc32; ImmBytes:0),
    (Kinds:$01; RegClass:brc32; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0),
    (Kinds:$03; RegClass:brc64; MemClass:bmc64; ImmBytes:0),
    (Kinds:$01; RegClass:brc64; MemClass:bmcNone; ImmBytes:0)
  );

  CBmiForms: array[0..25] of TBmiEncodingDescriptor = (
    (MnemonicIndex:0; Extension:beBMI1; FormTag:befRVM; VexPP:0; VexW:0; OpcodeMap:bom0F38; Opcode:$F2; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:0; OperandCount:3),
    (MnemonicIndex:0; Extension:beBMI1; FormTag:befRVM; VexPP:0; VexW:1; OpcodeMap:bom0F38; Opcode:$F2; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:3; OperandCount:3),
    (MnemonicIndex:1; Extension:beBMI1; FormTag:befRMV; VexPP:0; VexW:0; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:6; OperandCount:3),
    (MnemonicIndex:1; Extension:beBMI1; FormTag:befRMV; VexPP:0; VexW:1; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:9; OperandCount:3),
    (MnemonicIndex:2; Extension:beBMI1; FormTag:befVM; VexPP:0; VexW:0; OpcodeMap:bom0F38; Opcode:$F3; ModRegOperandIdx:-1; ModRegFixed:3; ModRmOperandIdx:1; VvvvOperandIdx:0; ImmediateOperandIdx:-1; OperandStart:12; OperandCount:2),
    (MnemonicIndex:2; Extension:beBMI1; FormTag:befVM; VexPP:0; VexW:1; OpcodeMap:bom0F38; Opcode:$F3; ModRegOperandIdx:-1; ModRegFixed:3; ModRmOperandIdx:1; VvvvOperandIdx:0; ImmediateOperandIdx:-1; OperandStart:14; OperandCount:2),
    (MnemonicIndex:3; Extension:beBMI1; FormTag:befVM; VexPP:0; VexW:0; OpcodeMap:bom0F38; Opcode:$F3; ModRegOperandIdx:-1; ModRegFixed:2; ModRmOperandIdx:1; VvvvOperandIdx:0; ImmediateOperandIdx:-1; OperandStart:16; OperandCount:2),
    (MnemonicIndex:3; Extension:beBMI1; FormTag:befVM; VexPP:0; VexW:1; OpcodeMap:bom0F38; Opcode:$F3; ModRegOperandIdx:-1; ModRegFixed:2; ModRmOperandIdx:1; VvvvOperandIdx:0; ImmediateOperandIdx:-1; OperandStart:18; OperandCount:2),
    (MnemonicIndex:4; Extension:beBMI1; FormTag:befVM; VexPP:0; VexW:0; OpcodeMap:bom0F38; Opcode:$F3; ModRegOperandIdx:-1; ModRegFixed:1; ModRmOperandIdx:1; VvvvOperandIdx:0; ImmediateOperandIdx:-1; OperandStart:20; OperandCount:2),
    (MnemonicIndex:4; Extension:beBMI1; FormTag:befVM; VexPP:0; VexW:1; OpcodeMap:bom0F38; Opcode:$F3; ModRegOperandIdx:-1; ModRegFixed:1; ModRmOperandIdx:1; VvvvOperandIdx:0; ImmediateOperandIdx:-1; OperandStart:22; OperandCount:2),
    (MnemonicIndex:5; Extension:beBMI2; FormTag:befRMV; VexPP:0; VexW:0; OpcodeMap:bom0F38; Opcode:$F5; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:24; OperandCount:3),
    (MnemonicIndex:5; Extension:beBMI2; FormTag:befRMV; VexPP:0; VexW:1; OpcodeMap:bom0F38; Opcode:$F5; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:27; OperandCount:3),
    (MnemonicIndex:6; Extension:beBMI2; FormTag:befRVM; VexPP:3; VexW:0; OpcodeMap:bom0F38; Opcode:$F6; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:30; OperandCount:3),
    (MnemonicIndex:6; Extension:beBMI2; FormTag:befRVM; VexPP:3; VexW:1; OpcodeMap:bom0F38; Opcode:$F6; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:33; OperandCount:3),
    (MnemonicIndex:7; Extension:beBMI2; FormTag:befRVM; VexPP:3; VexW:0; OpcodeMap:bom0F38; Opcode:$F5; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:36; OperandCount:3),
    (MnemonicIndex:7; Extension:beBMI2; FormTag:befRVM; VexPP:3; VexW:1; OpcodeMap:bom0F38; Opcode:$F5; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:39; OperandCount:3),
    (MnemonicIndex:8; Extension:beBMI2; FormTag:befRVM; VexPP:2; VexW:0; OpcodeMap:bom0F38; Opcode:$F5; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:42; OperandCount:3),
    (MnemonicIndex:8; Extension:beBMI2; FormTag:befRVM; VexPP:2; VexW:1; OpcodeMap:bom0F38; Opcode:$F5; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:2; VvvvOperandIdx:1; ImmediateOperandIdx:-1; OperandStart:45; OperandCount:3),
    (MnemonicIndex:9; Extension:beBMI2; FormTag:befRM; VexPP:3; VexW:0; OpcodeMap:bom0F3A; Opcode:$F0; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:-1; ImmediateOperandIdx:2; OperandStart:48; OperandCount:3),
    (MnemonicIndex:9; Extension:beBMI2; FormTag:befRM; VexPP:3; VexW:1; OpcodeMap:bom0F3A; Opcode:$F0; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:-1; ImmediateOperandIdx:2; OperandStart:51; OperandCount:3),
    (MnemonicIndex:10; Extension:beBMI2; FormTag:befRMV; VexPP:2; VexW:0; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:54; OperandCount:3),
    (MnemonicIndex:10; Extension:beBMI2; FormTag:befRMV; VexPP:2; VexW:1; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:57; OperandCount:3),
    (MnemonicIndex:11; Extension:beBMI2; FormTag:befRMV; VexPP:1; VexW:0; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:60; OperandCount:3),
    (MnemonicIndex:11; Extension:beBMI2; FormTag:befRMV; VexPP:1; VexW:1; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:63; OperandCount:3),
    (MnemonicIndex:12; Extension:beBMI2; FormTag:befRMV; VexPP:3; VexW:0; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:66; OperandCount:3),
    (MnemonicIndex:12; Extension:beBMI2; FormTag:befRMV; VexPP:3; VexW:1; OpcodeMap:bom0F38; Opcode:$F7; ModRegOperandIdx:0; ModRegFixed:-1; ModRmOperandIdx:1; VvvvOperandIdx:2; ImmediateOperandIdx:-1; OperandStart:69; OperandCount:3)
  );

implementation

end.
